### ISSUE TITLE
Feature request: disable spell combos/Auto Loan/sugar frenzy when Interest debuff is active

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#104]
sometimes a spell combo will trigger in the middle of an Interest debuff, which causes much less production from that combo. I would like if combos/Loans/sugar frenzy did not activate if there was an Interest debuff active, either as a togglable option or tweaking the current automation to check for this. 

I'm not sure if this should include loan 3 or not due to how long it lasts.

**Comment by erbkaiser** [comment]
Should be possible. Loans already check for an existing, user settable buff, but I can also add an option they will not kick in if loan 1 or 2 is still on interest.

**Comment by erbkaiser** [comment]
Implemented in this way:
-the minimum Frenzy for Auto Cast is now also applied to the Double Cast and 100% Consistency Combos (should in practice always allow the combos since they already requires existing frenzies, but if you are in a double interest reoayment, it will likely block it)

-if Interest 1, 2, or 3 are active AND there is a minimum frenzy set for 'Automatically take loans during click buffs', it will not take the loan or activate sugar frenzy.
