### ISSUE TITLE
Messed up timers on load if CCSE is active

### ISSUE THREAD

**Issue by erbkaiser** [erbkaiser/FrozenCookies#20]
Something in CSSE is causing research lab notification spam and elder covenant switches appearing, as well as constantly buy elder pledges and seasons. This is not an issue with FC and will not be further researched.

**Comment by erbkaiser** [comment]
CCSE bug: https://github.com/klattmose/klattmose.github.io/issues/47

**Comment by TylorBane** [comment]
i know this has since been closed as the issue is on ccse, but how hard would it be to either make frozen compatible, or if not just use ccse as a dependency to force compatibility? this has been a long going issue for a long long time now (so long that i dont even know if it's still an issue and just havent tried again as of late)

**Comment by erbkaiser** [comment]
I have no idea what part of CCSE is causing the error, and CCSE code is complex. I personally won't be able to make them work together.

Pre-2.046 CCSE worked fine with FC so it has to be something that changed when CCSE was updated, but even comparing commits doesn't make it clear to me what might be the cause.
Unless the CCSE author wants to look at this I don't think there's a solution.

**Comment by TylorBane** [comment]
the issue that's on the ccse's git (where i got the link to this closed one) has had absolutely no attention from klat, so im slowly getting the assumption that they consider frozen to be a cheat mod and just dont care enough to give users help with the issue

**Comment by erbkaiser** [comment]
Possibly, or Klatt just doesn't feel like looking at code he did not write. I reject the notion FC is a cheat mod though. It automates things sure, but it does nothing you could not do yourself or with other tools.

I do not use CCSE and haven't found any mod that requires it, does not cheat in some way - like adding super powered sugar effects -, or does something another mod that does not need CCSE does, so I am also not that interested into deep diving its code to find out what the problem exactly is.

Another issue is that I am, to the best of my knowledge, the only one maintaining an updated FC fork (all the others are stuck on the 2.031 version or older), and I am certainly not a Javascript expert and to be frank, hardly know how certains part of FC work to begin with. So even on the FC side I don't think anyone is looking into what the problem with CCSE is.

**Comment by TylorBane** [comment]
the only reason i want ccse to work with frozen cookies is because i've been wanting a good automatic trading mod as im a lazy fuck and that much math hurts my brain, so these mods are the reason why i've been so invested on this issue
[Idle Trading](https://steamcommunity.com/sharedfiles/filedetails/?id=2685515551) and
[Insugar Trading](https://steamcommunity.com/sharedfiles/filedetails/?id=2698330731)

**Comment by erbkaiser** [comment]
Will be fixed by the next CCSE update for game version 2.05.

**Comment by TylorBane** [comment]
sick, awesome, if you dont mind my asking, do you have any idea when the steam workshop versions will be updated to the patch?

**Comment by erbkaiser** [comment]
I plan to update FC as soon as the new build goes live on Steam. The beta is basically ready.
CCSE, I expect the same.
