### ISSUE TITLE
Auto cast FTHOF seems buggy

### ISSUE THREAD

**Issue by hnns88** [erbkaiser/FrozenCookies#22]
I had it happen several times that it casted Haggler's Charm with none of the triggers (Clot, Blab, Storm Drop, Ruin) being the next FTHOF spell. Especially annoying if that happens during a build-up of a big combo (active Frenzy, waiting for Building Special with BS + 2x CF lined up in FTHOF to use with double cast and sugar lump spending). Is that somehow expected behaviour or a bug?

Also the Auto FTHOF combo seems to switch autobuy off sometimes which is annoying if you expect Godzamok to work and rebuy stuff automatically during big combos.

**Comment by hnns88** [comment]
It also does not take into account that the FTHOF outcome changes if a DF is active (does it also change during a CF from a normal spawn GC?). Just witnessed that the predicted CF got wasted because a DF triggered Godzamok and FTHOF was casted only to spawn a Lucky cookie.

**Comment by Darkroman** [comment]
As the original writer of the auto FTHOF combo code, I'm not sure why he put in the "smart" FTHOF auto cast outcomes into the combo, they should be separate. In other words it should always cast haggler's charm if auto FTHOF combo is on until it sees a BS/EF+CF in the next spell queue. I would do my own updated port of FC but I'm too lazy right now (older FC ports are broken due to some sort of javascript map error). As far as it seeing DF no I don't think I ever wrote it to change behavior upon an active DF. Now that I think about it, it could be remedied pretty easily actually if it checks to see if DF is active before ever casting FTHOF when lucky is the next spell.

**Comment by Darkroman** [comment]
Thinking about it more I believe it would be best if upon seeing an active DF buff it just exits the auto FTHOF combo function completely that way it wouldn't interfere with anything and would keep its intended state.

**Comment by erbkaiser** [comment]
I'll need to check it out some more, thanks for the report. The DF check definitely is possible to do, I think I noticed that myself. It's annoying behaviour from the base game that it disables a click frenzy FTHOF :/

The reason I put in the smart behaviour is that I like using it as a smarter FTHOF with all 'good' spells being cast, but it _also_ doing the combo when possible.

**Comment by Darkroman** [comment]
Fair enough, it's your port. You do what you want with it :)
