### ISSUE TITLE
Disable Golden Cookie Bank

### ISSUE THREAD

**Issue by Bjoern-B** [erbkaiser/FrozenCookies#27]
Any chance to get an option to just disable the golden cookie bank I get its more efficient to have that money for the golden cookies but I think it would be nice to just have an option so that the money gets spend anyways

**Comment by Bjoern-B** [comment]
![Screenshot 2022-06-18 194945](https://user-images.githubusercontent.com/38884487/174450607-c9664052-3097-4e00-8317-75a0d4bda127.png)
Like I dont see a point in having to wait 21h just to gain the maximum from a golden cookie it would be way more efficient to just spend it at that point

**Comment by erbkaiser** [comment]
I probably won't do this since it's referenced at so many spots in the code it'll be hell to optionally disable this, but I'm not ruling it out completely either.

You can of course ignore it during early game and just buy the next suggested purchase anyway. By the time you get to the decillions and better, refilling the bank is a matter of minutes at most.
