### ISSUE TITLE
Add a buy all upgrades function

### ISSUE THREAD

**Issue by erbkaiser** [erbkaiser/FrozenCookies#55]
Also, would you be able to add a buy all upgrades switch for easier 1000 ascension pace

_Originally posted by @Jaxlyfe in https://github.com/erbkaiser/FrozenCookies/issues/54#issuecomment-1179436396_

**Comment by ghost** [comment]
This would speed things up tremendously. I don't think you'd even need to make it efficient, just have it bypass the auto buy every second or half second?

Obviously, do it however you intend to do it, but that would be my suggestion. Until you come up with a better optimization so it can be used more broadly, if that was ever your intent, I think just a simple timer would still do wonders for the suggested use case. That way, you can send at least a rough version of the feature out as soon as you like, rather than needing extra development time

For a rough estimate of time saved, I just used my phone's stopwatch to see how long a regular ascension took vs an ascension with a macro clicking buy all upgrades indiscriminately once every 500ms. Without macro: 75-80 seconds. With macro: 11-12 seconds. For reference, I'm at prestige level 588 billion (and some change), and I timed with and without macro twice. The only possible problem I can see with my methodology is that I'm dropping hella frames, but considering how similar the times were each time it doesn't seem like it caused too much variance. I used the most efficient settings I could, to give poor JavaScript a chance to breathe. If anyone is desperate for some more details I can try my best to offer them but I think I've taken up enough time and space here

Sincere apologies if you've already got a whole plan for this and my lengthy comment hasn't provided any useful insight.

**Comment by erbkaiser** [comment]
It's on the list to do. Thanks for the extra info.

**Comment by erbkaiser** [comment]
Implemented!

New option is under 'other upgrades'. It was really annoying to do since I can't figure out a good way to filer out the research upgrades, but it should be working fine now.
I can confirm enablign it really decreases the time until the first HC is earned.

The way I implemented it, it will keep hitting the button for as long as it can afford any upgrade, until the first new HC is earned.

**Comment by Hringingy** [comment]
Can this work with Blacklist: Hardcore mode enabled? This would help to further speed things up by reducing lag

**Comment by erbkaiser** [comment]
It should work yes. I completely ignore blacklists in the check. The only prerequisite is owning the heavenly upgrade Inspired Checklists as that unlocks the buy all button in the first place.

**Comment by erbkaiser** [comment]
Actually, no, it won't. Hardcore means buying no upgrades until the goal is met so it will block upgrades from appearing as recommendations while active, which means the buy all upgrades check never happens as long as that blacklist is active.

**Comment by Hringingy** [comment]
Would it be possible to implement?

**Comment by erbkaiser** [comment]
Not easily. I would need to rewrite how the buy all is triggered.
You don't need it, though. As implemented now any time autobuy queues an upgrade, it will hit buy all instead, so until the first hc is earned it works the same.

**Comment by Hringingy** [comment]
I feel like it would make getting the Endless Cycle achievement significantly faster, but I understand if it can't be done. Still, I really do appreciate this new feature as it currently is.
