### ISSUE TITLE
Auto Godzamok autosell cap

### ISSUE THREAD

**Issue by valkyriaivan** [erbkaiser/FrozenCookies#71]
Im currently using Auto Godzamok with a Mine and Facotry limit of 600 each. When a click frenzy is activated, it only sells a total of 1000 buildings resulting in a 1000% buff.
Is the limit of 1000 efficient? Other mods sell buildings repitedly while the click frenzy is active. Resulting in sometimes 50-75k% buff. I thought maybe efficiency is the reason, but I compared both and even if the one selling contantly results in an initial slow return, in general after the frenzy ends, it seems like it got better results. 
I don't have exact data, but it seems like limiting it to 1000 is less efficient. 
Why is it capped at 1000?

**Comment by erbkaiser** [comment]
Basically, legacy code.
When running without building caps, I found that buying back over 500 of both can lead to rapidly diminishing results.

You're right in that it should respect the building caps though, so I'll change that next time I update the mod. If running uncapped it will limit to 500, otherwise it will limit to the set caps.

**Comment by valkyriaivan** [comment]
I think I explained myself badly. The building cap is working correctly. I think it sells 500 of each and buys 500 back without going over the cap.
My concern was regarding if it was only selling 1000 total instead of repatedly selling and buying 500. Since other mods don't stop selling after reaching 1000 I was wondering if it lead to better results if you stop at 1000.

**Comment by erbkaiser** [comment]
No, I understand what you mean.

The way my fork works now is that it will never sell more than 500 mines or factories. This is something I implemented back when I started forking it, since I was experimenting with which building was the best one to sacrifice to Godz. Even with limits set, loading a save with over that limit would potentially ruin the Godz effect by buying back for more cookies than were earned.
After I got it working right I never removed the cap as I usually limit my mines and factories to around 550 so I simply did not notice.

1000 is 'good enough': it gives a good boost and will never not pay for itself. But it's possible to do better.

I'm going to change it so it only hard caps if there is no limit set, and will respect the set limit otherwise. That way, you can get a boost of 1200 if you limit both to 600, or higher if you wish, and it's up to you to see where the selling and rebuying stops being efficient.

I'll test the change in a few hours and if it works well, push it to live.

**Comment by Hringingy** [comment]
What about rapid spam of selling/rebuying mines and factories over and over? I've played around with mods that would do that and it led to insanely powerful Godzamok buffs.

**Comment by erbkaiser** [comment]
There is no functional difference between selling/rebuying 100 buildings 10 times and doing 1000 buildings once, other than that in the latter case, the full devastation buff is maxed and in the former case it ramps up from 100 to 1000 as the buff depletes.
Frozen Cookies will already repeat the sell/rebuy cycle if devastation ends while a click buff is still active (thus, up to three times per buff).

If you know of a more efficicient guaranteed number of buildings to sell and rebuy during a normal click buff, I'm all ears. From my own testing I know it's somewhere between 400 mines & factories (net win) and 800 mines and factories (net loss).

**Comment by Hringingy** [comment]
Using my own save in issue #70 as an example, I have Mines and factories capped at 925 and 900, respectively. With a mod that spams autosell/rebuys almost every frame, I can drop the cap by only about 200 each for the cost to become negligible even with the hundreds of times that other mod spams selling over the 10s of Godzamok's buff. The ~1800 buildings sold only once every 10 seconds is far less than ~1400 buildings being sold dozens of times per second.

**Comment by erbkaiser** [comment]
The 500 cap is gone now. Instead, auto-Godzamok will limit itself to rebuying up the cap, if set. That should fix the issue @valkyriaivan mentioned.

@Hringingy Rapidly reselling/rebuying thousands of buildings is impossible to script in a way that it will work for all possible setups, which is a goal of FC. The experimental combos already break the design a little.
The only way I can implement it while keeping the mod design goals (as I see them) in place is to script a second auto-Godzamok system, which already exists for the 100% combo and I have no current plans to create a more generalized version.

**Comment by Hringingy** [comment]
That's ok, As I see it, the spam could be considered kinda OP
