### ISSUE TITLE
Feature Request: Preserve Swap mode for Auto Pantheon

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#86]
In order for me to use the new Auto-Cyclius mode that you've implemented, I have to turn Auto Pantheon off and manually slot in the gods one at a time each hour or else I'd end up having to wait 20-21 hours for my swaps to refill. I'd like to request an option in the Pantheon that will slot my preset gods one at a time and only when my swaps have refilled.

I admit I'm not too familiar with Cyclius swapping so I understand if this feature does not get implemented as I have no idea how difficult it may be to integrate this with Auto-Cyclius

**Comment by erbkaiser** [comment]
Enabling Auto-Cyclius turns off the Auto-Pantheon, but it will use any slotted gods to swap them back in when Cyclius needs to be unslotted.

The intended use scenario is to set up the Pantheon with Auto-Pantheon or manually, and then enable Auto-Cyclius. No manual swapping needed.
At worst, this means waiting for one swap to refill before Cyclius can be slotted.
This will only happen after ascension or when first enabling both options and I do not have a real good workarond for this that still leaves in some automation possibility.

Cyclius will swap 4 times over a day in the ruby-jade mode, and 12 times using the all slots mode. This should never take up more than two worship slots.

**Comment by erbkaiser** [comment]
Keep in mind that once auto-C is active, it will keep the same three gods (hopefully diamond and ruby) until Cyclius is unslotted.

This means that if you are running Godz-Moka-Muri with the two slot Auto-C method, for most of the day it will oscillate between Godz-Moka-Cycl and Godz-Cycl-Moka, only returning to Godz-Moka-Muri after 6PM UTC.

**Comment by Hringingy** [comment]
The problem is if Auto Pantheon slots 3 gods at the start of a run (I'm using Godz-Moka-Muri) I run out of swaps immediately and I have to wait 16 hours to get a single swap back. With a "one at a time/Preserve Swap" mode, it'd be possible to have all three swaps in only 3 hours.

Is Godz-Cycl-Moka truly more efficient than Godz-Moka-Muri? If so, how do I set up for that? Wouldn't the pantheon become Godz-Cycl-Muri if I set Auto Panteon default to Godz-Moka-Muri?

More importantly, I just tried to disable Auto Pantheon and use Cyclius manually a little bit ago, but it caused MASSIVE LAG with FC the moment Cyclius was slotted. It seems the Efficiency calculator does not like having a constantly fluctuating modifier to CpS causing it to recalculate every second. Is there a way to deal with this?

**Comment by erbkaiser** [comment]
The way to set it up _directly_ after ascending is to not enable the Auto Pantheon function itself but only pick the three desired gods, then manually slot Godz, Moka, and Cyclius in the proper slots. I hope I made that clear in the readme.
If I can find some way to automate this better in the future I'll try to do so. 

There is no fix for the efficiency calculations, since Cyclius changes CpS every second it will cause lag. If you're concerned about that I suggest not using Cyclius until you're past the point where almost all upgrades are bought (around the time of your 650th Cortex baker). 

On average, Cyclius with two slots will give about an 8% CpS boost throughout the 18 hours it can be active. A 6% boost throughout the day if it is able to use all three slots. Whether or not that is more efficient than a constant clicking bonus from Muridal, which itself is reliant on how fast your client can register clicks to begin with, is not something I feel like calculating.

**Comment by Hringingy** [comment]
I was more so talking about moving Moka off of Ruby into Jade and whether or not the loss of Milk power from that is worth Cyclius' CpS bonus. I don't think it is, but I could be wrong.

for clicking bonuses like Muridal, I just use shorthand calculations that assume all of my cookies come from clicking and not passive production, such as:

Muridal in Jade Slot
(1+(.05 clicking power)) * (1-(.01 penalty to building production)) = 1.0395 effective multiplier to production

the actual bonus is tecnically less than 1.0395, but the difference is negligible especially during Godz boosted Click Frenzies which is where most of the "power" of the run comes from.

**Comment by erbkaiser** [comment]
I just updated auto-Cyclius so that it can work with Supreme Intellect.
It also now should work better after ascending or when first enabling with no gods slotted yet: auto-C will first set Cyclius to the desired slot, then set the auto-Pantheon gods for the first two slots in whichever slots aren't already filled, if possible. This means the god set in auto-Pantheon for Jade will only be set if Cyclius is not, otherwise it will use the Diamond and Jade gods in the two slots Cyclius is not in.

Cyclius admittedly has limited use, so I suggest just not using it if it doesn't fit your playstyle.
